### PR TITLE
Update to 2.4.1 and AU

### PR DESCRIPTION
**Pull request by pwindle**
Here's an up to date package for OpenVPN with an AU automatic upgrader script added. I saw your comment from over a month ago that you have it in the pipeline but I see no developments since then. I thought perhaps this could be used, atleast until you have a more official system in place? I say more official because there seems to not yet be a good way of getting the latest version number (see line 3 in update.ps1).

Feel free to tell me if I've misinterpreted the situation here or if my code is no good. Thanks for all the work on this.

### CODE REVIEW

**Comment by wget** [comment]
@proticity Thanks a lot. Indeed I had no time to implement AU for now :)

Actually, automation can be achieved thanks to [this link](http://build.openvpn.net/downloads/releases/latest/). Let me know if you want to implement these changes. Or I can do it by my self if you want :)

**Comment by pwindle** [comment]
@wget Ah yes that link works much better I'll look into that now.

**Comment by pwindle** [comment]
New release URL is now implemented.

**Comment by pwindle** [comment]
It is downloading the whole installer just to check for a latest version... will fix this soon.

**Review by wget — COMMENTED** [review]
The problem with the change of id is that it will change the package name on chocolatey. Do we have another solution? When cloning, the foldername could be specified as openvpn and it should be fixed.

**Comment by pwindle** [comment]
@wget I think I'll just change it back to the original name. I was cloning from that module so it was giving me problems with the automatic folder naming. If you clone your entire package collection that should work well, but I wasn't doing that because I haven't setup the SSH and so on so it was failing to clone. 

"When cloning, the foldername could be specified as openvpn and it should be fixed."
Do you mean it can do that automatically? If so I don't know how.

**Comment by mattock** [comment]
And in the end I'd like to see the commits squashed to a few. Right now there are almost as many commits as there are lines changed :smile:

**Comment by pwindle** [comment]
@mattock It is a mess. Will fix shortly.

**Comment by wget** [comment]
@proticity A few cosmetic things before I merge your commit:
- You published `update.ps1.orig` , you will need to squash again :p 
- Please remove the `new` in the public key file name. Like it was previously.
- I know PowerShell syntax is insane, but you are mixing camelcase and underscore syntaxes like with `$version_page`. Use camelcase as much as possible in order to respect the .NET syntax as much as please :)

Thanks again for your hard work. AU was a requirement to make openvpn an official chocolatey package.

**Comment by pwindle** [comment]
@wget OK, It should now match your specifications. I hope I've finally squashed all traces of my mistakes :)

Thank you too.

**Pull request merged**
